namespace DuckGame;

public class KeyHelper
{
    public static char KeyToChar(Keys key)
    {
        return key switch
        {
            Keys.A => 'A',
            Keys.B => 'B',
            Keys.C => 'C',
            Keys.D => 'D',
            Keys.E => 'E',
            Keys.F => 'F',
            Keys.G => 'G',
            Keys.H => 'H',
            Keys.I => 'I',
            Keys.J => 'J',
            Keys.K => 'K',
            Keys.L => 'L',
            Keys.M => 'M',
            Keys.N => 'N',
            Keys.O => 'O',
            Keys.P => 'P',
            Keys.Q => 'Q',
            Keys.R => 'R',
            Keys.S => 'S',
            Keys.T => 'T',
            Keys.U => 'U',
            Keys.V => 'V',
            Keys.W => 'W',
            Keys.X => 'X',
            Keys.Y => 'Y',
            Keys.Z => 'Z',
            Keys.D0 => '0',
            Keys.D1 => '1',
            Keys.D2 => '2',
            Keys.D3 => '3',
            Keys.D4 => '4',
            Keys.D5 => '5',
            Keys.D6 => '6',
            Keys.D7 => '7',
            Keys.D8 => '8',
            Keys.D9 => '9',
            Keys.OemBackslash => '\\',
            Keys.OemCloseBrackets => ']',
            Keys.OemComma => ',',
            Keys.OemMinus => '-',
            Keys.OemOpenBrackets => '[',
            Keys.OemPeriod => '.',
            Keys.OemPipe => '|',
            Keys.OemPlus => '+',
            Keys.OemQuestion => '?',
            Keys.OemQuotes => '"',
            Keys.OemSemicolon => ';',
            Keys.OemTilde => '~',
            Keys.NumPad0 => '0',
            Keys.NumPad1 => '1',
            Keys.NumPad2 => '2',
            Keys.NumPad3 => '3',
            Keys.NumPad4 => '4',
            Keys.NumPad5 => '5',
            Keys.NumPad6 => '6',
            Keys.NumPad7 => '7',
            Keys.NumPad8 => '8',
            Keys.NumPad9 => '9',
            _ => ' ',
        };
    }
}
